# Generated by Django 3.0.5 on 2022-11-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradmin',
            old_name='passw',
            new_name='pas',
        ),
    ]
